### Numpy Part 1 : Numpy Fundamental and Essential

In [1]:
# Kita import library
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:\Ruang Lab\Kelas Machine Learning\Day 3\iris.csv")

In [3]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
# Kita tampilin beberapa kolom
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [5]:
# Kita ambil beberapa kolom yah
iris_data_numeric = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)','petal width (cm)']].values

### Numpy Array

In [6]:
# <!-- ini adalah python list, tipe datanya masih list -->
python_list = [1,2,3,4,5]

# <!-- Konfersi array-->
array_from_list = np.array(python_list)

In [7]:
print(python_list)
print(array_from_list)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [8]:
array_from_list[1]

np.int64(2)

In [9]:
# untuk membuat array 0
# np.zeros()

zeros_array = np.zeros((3,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# untuk membuat matriks nilai 1
# np.ones
ones_array = np.ones((3,3,3))
ones_array

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
# np.arrange() -> similiar with for loop (start, stop, step)
arrange_array = np.arange(0, 10, 1)
arrange_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Random Value numpy array

In [12]:
# np.random.rand() -> random float
# np.random.randint() -> random int

In [13]:
# Untuk mengambil nilai random dari 0-1
random_float_array = np.random.rand(1)
random_float_array

array([0.08655409])

In [14]:
random_int_array = np.random.randint(0,10,size=(3,3),dtype='int64')
random_int_array

array([[4, 3, 7],
       [3, 8, 6],
       [0, 0, 3]])

### Reshaping array
##### mengotak atik bentuk matriks biar bisa di kalkulasi

In [15]:
# Matriks Multiplication, perkalian matriks
# syaratnya inget .. x b = b x ..
# Tapi misal 2 x 5 kita kali 3 x 5 maka harus di tranpose

# kita coba yah
old_array = np.arange(1,11)
old_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Mengubah bentuk 1x10 menjadi 5x2
# kemungkinan yang bisa 5x2 atau semuanya yang hasilnya 10
old_array_reshaped = old_array.reshape((5,2))
old_array_reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Indexing and Slicing

In [17]:
iris_data_numeric[0,0]

np.float64(5.1)

In [18]:
# [start:stop:step]
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
# [row,column] -> [start:end:step, start:end:step]
iris_data_numeric[0:5,0:2]

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [20]:
iris_data_numeric[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [21]:
# akses semuanya
iris_data_numeric[:,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [22]:
sepal_length_gt_5 = iris_data_numeric[iris_data_numeric[:, 1] > 4]
sepal_length_gt_5

array([[5.7, 4.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2]])

### Operasi Numpy (artimatika & aggregation)

In [23]:
data15 = np.arange(1,6)
data510 = np.arange(6,11)

In [24]:
data_sum = data15 + data510
data_sum

array([ 7,  9, 11, 13, 15])

In [25]:
data_substrac = data510 - data15
data_substrac

array([5, 5, 5, 5, 5])

### Numpy Part 2 : Broadcasting

In [ ]:
# Sekarang kita belajar math
# np.sqrt()

In [27]:
data = np.random.randint(10,100, size = (3,3))
data

array([[30, 59, 15],
       [30, 27, 37],
       [23, 51, 70]], dtype=int32)

In [ ]:
# kenapa tidak menggunakan ? import math as m
# Karena math itu untuk 1 entitas aja, sementara array banyak kan
# array kumpulan entitas

Data_sqrt = np.sqrt(data)
Data_sqrt

array([[5.47722558, 7.68114575, 3.87298335],
       [5.47722558, 5.19615242, 6.08276253],
       [4.79583152, 7.14142843, 8.36660027]])

In [ ]:
# np.log (logaritmik)
data_log = np.log(Data_sqrt)
data_log

array([[1.70059869, 2.03876872, 1.3540251 ],
       [1.70059869, 1.64791843, 1.80545896],
       [1.56774711, 1.96591282, 2.12424762]])

In [33]:
data_log_2 = np.log2(data)
data_log_2

array([[4.9068906 , 5.88264305, 3.9068906 ],
       [4.9068906 , 4.7548875 , 5.20945337],
       [4.52356196, 5.67242534, 6.12928302]])

In [ ]:
# np.exp(), np.sin(), np.cos()

### Dot Product & Matrix Multiplication

In [36]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [38]:
hasil = np.dot(v1,v2)
hasil


np.int64(32)

In [ ]:
# dot untuk matrix multiplication
m1 = np.array([[2,3,1],
               [7,6,1]])

m2 = np.array([[1,2],
               [5,3],
               [1,1]
               ])

In [40]:
hasil = np.dot(m1,m2)
hasil

array([[18, 14],
       [38, 33]])

In [41]:
# Tapi ada cara lain
hasil = m1 @ m2
hasil

array([[18, 14],
       [38, 33]])

In [42]:
hasil = np.matmul(m1,m2)
hasil

array([[18, 14],
       [38, 33]])

### Broadcasting

In [53]:
# Idenya adalah ketika kita memiliki matriks yang ngga sama.
# inget syarat matriks 2x3 * 3x2, dimana a x b = b x c... 
# Nah disitu problemnya, gimana kalau ternyata berbeda ??
# Contoh 2x3 * 1x1


v = np.array([1,2,3])
s = 10

hasil = v - s
hasil

# jadi yang dimensi kecil akan menyesuaikan yang besar

array([-9, -8, -7])

In [ ]:
# Matrix dengan vector
M = np.array([[1,2,3],
              [4,5,6]])

v = np.array([10,20,30])

# len(v) == 1 -> scalar
# len(v.column) == c
# len(v.row) == r

hasil = M + v
hasil

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
M = np.array([[1,2,3],
              [4,5,6]])

v = np.array([[100],
              [200]])

In [52]:
iris_data_numeric_tambahan = iris_data_numeric[:, 3]
iris_data_numeric_tambahan

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

### np.concatenate

In [59]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6]])

array_gabungan = np.concatenate((array1, array2), axis = 0)
array_gabungan

# Acis 0 - row
# axis 1 - column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5],[6]])

array_gabungan = np.concatenate((array1, array2), axis = 1)
array_gabungan

# Acis 0 - row
# axis 1 - column

array([[1, 2, 5],
       [3, 4, 6]])